// Auto-generated by tools/convert_pets.py — do not edit by hand.
#pragma once
#include <Arduino.h>
#include "../pet.h"

static const char CRAB_SLEEP_0[] PROGMEM =
    "     zzZ\n"
    " (v)(-,,- )(v)\n"
    "  /|      |\\\n"
    " _/ |____| \\_";
static const char CRAB_SLEEP_1[] PROGMEM =
    "      zZ\n"
    " (v)(-,,- )(v)\n"
    "  /|      |\\\n"
    " _/ |____| \\_";
static const char* const CRAB_SLEEP[] PROGMEM = {CRAB_SLEEP_0, CRAB_SLEEP_1};

static const char CRAB_IDLE_0[] PROGMEM =
    " (V)(;,,;)(V)\n"
    "  /|      |\\\n"
    " _/ |____| \\_";
static const char CRAB_IDLE_1[] PROGMEM =
    " (V)(;,,; )(V)\n"
    "  /|      |\\\n"
    " _/ |____| \\_";
static const char CRAB_IDLE_2[] PROGMEM =
    "(V) (;,,;)(V)\n"
    "  /|      |\\\n"
    " _/ |____| \\_";
static const char* const CRAB_IDLE[] PROGMEM = {CRAB_IDLE_0, CRAB_IDLE_1, CRAB_IDLE_2};

static const char CRAB_BUSY_0[] PROGMEM =
    " >V<(◎,,◎)>V<\n"
    "  /|      |\\\n"
    " _/ |____| \\_";
static const char CRAB_BUSY_1[] PROGMEM =
    " (V)(◎,,◎)(V)\n"
    "  /|      |\\\n"
    " _/ |____| \\_";
static const char* const CRAB_BUSY[] PROGMEM = {CRAB_BUSY_0, CRAB_BUSY_1};

static const char CRAB_ATTENTION_0[] PROGMEM =
    "\\V/       \\V/\n"
    "   (°,,°)!\n"
    "  /|      |\\\n"
    " _/ |____| \\_";
static const char CRAB_ATTENTION_1[] PROGMEM =
    "\\V/       \\V/\n"
    "   (°,,°)!!\n"
    "  /|      |\\\n"
    " _/ |____| \\_";
static const char* const CRAB_ATTENTION[] PROGMEM = {CRAB_ATTENTION_0, CRAB_ATTENTION_1};

static const char CRAB_CELEBRATE_0[] PROGMEM =
    "\\V/  ★  \\V/\n"
    "   (^,,^)\n"
    "  /|      |\\\n"
    " _/ |____| \\_";
static const char CRAB_CELEBRATE_1[] PROGMEM =
    " \\V/ ♪ \\V/\n"
    "   (^,,^)\n"
    "   |      |\n"
    "  _/|____|\\_ ";
static const char CRAB_CELEBRATE_2[] PROGMEM =
    "\\V/  ✧  \\V/\n"
    "   (^,,^)\n"
    "  /|      |\\\n"
    " _/ |____| \\_";
static const char* const CRAB_CELEBRATE[] PROGMEM = {CRAB_CELEBRATE_0, CRAB_CELEBRATE_1, CRAB_CELEBRATE_2};

static const char CRAB_DIZZY_0[] PROGMEM =
    " (v)(@,,@)(v)\n"
    "  /|      |\\\n"
    "  _/|____|\\_ ";
static const char CRAB_DIZZY_1[] PROGMEM =
    "  (v)(×,,×)(v)\n"
    "   /|      |\\\n"
    "  _/ |____| \\_";
static const char* const CRAB_DIZZY[] PROGMEM = {CRAB_DIZZY_0, CRAB_DIZZY_1};

static const char CRAB_HEART_0[] PROGMEM =
    "  ♥       ♥\n"
    " (V)(♡,,♡)(V)\n"
    "  /|      |\\\n"
    " _/ |____| \\_";
static const char CRAB_HEART_1[] PROGMEM =
    " ♥  ♥   ♥  ♥\n"
    " (V)(♡,,♡)(V)\n"
    "  /|      |\\\n"
    " _/ |____| \\_";
static const char* const CRAB_HEART[] PROGMEM = {CRAB_HEART_0, CRAB_HEART_1};

static const PetFrames CRAB_PET PROGMEM = {
    "crab",
    CRAB_SLEEP, 2,
    CRAB_IDLE, 3,
    CRAB_BUSY, 2,
    CRAB_ATTENTION, 2,
    CRAB_CELEBRATE, 3,
    CRAB_DIZZY, 2,
    CRAB_HEART, 2,
};
