// Auto-generated by tools/convert_pets.py — do not edit by hand.
#pragma once
#include <Arduino.h>
#include "../pet.h"

static const char FOX_SLEEP_0[] PROGMEM =
    "   /\\_/\\  zzZ\n"
    "  ( -.- )\n"
    "  />🦊~~~~~\n"
    "   \\___/";
static const char FOX_SLEEP_1[] PROGMEM =
    "   /\\_/\\   zZ\n"
    "  ( -.- )\n"
    "  />🦊~~~~~\n"
    "   \\___/";
static const char* const FOX_SLEEP[] PROGMEM = {FOX_SLEEP_0, FOX_SLEEP_1};

static const char FOX_IDLE_0[] PROGMEM =
    "   /\\_/\\\n"
    "  ( o.o )\n"
    "  /> ^ <\\\n"
    " /_|___|_\\~~";
static const char FOX_IDLE_1[] PROGMEM =
    "   /\\_/\\\n"
    "  ( -.- )\n"
    "  /> ^ <\\\n"
    " /_|___|_\\~~";
static const char FOX_IDLE_2[] PROGMEM =
    "   /\\_/\\\n"
    "  ( o.o )?\n"
    "  /> ^ <\\\n"
    " /_|___|_\\ ~";
static const char* const FOX_IDLE[] PROGMEM = {FOX_IDLE_0, FOX_IDLE_1, FOX_IDLE_2};

static const char FOX_BUSY_0[] PROGMEM =
    "   /\\_/\\\n"
    "  ( ◎.◎ )\n"
    "  /> ^ <\\ ⌨\n"
    " /_|___|_\\~~";
static const char FOX_BUSY_1[] PROGMEM =
    "   /\\_/\\\n"
    "  ( ◎.◎;)\n"
    "  /> ^ <\\⌨\n"
    " /_|___|_\\ ~";
static const char* const FOX_BUSY[] PROGMEM = {FOX_BUSY_0, FOX_BUSY_1};

static const char FOX_ATTENTION_0[] PROGMEM =
    "   /!_/!\\\n"
    "  ( °o° )\n"
    "  /> ^ <\\\n"
    " /_|___|_\\~~ !";
static const char FOX_ATTENTION_1[] PROGMEM =
    "   /!_/!\\\n"
    "  ( °o° )!\n"
    "  /> ^ <\\\n"
    " /_|___|_\\~~~!";
static const char* const FOX_ATTENTION[] PROGMEM = {FOX_ATTENTION_0, FOX_ATTENTION_1};

static const char FOX_CELEBRATE_0[] PROGMEM =
    "   /\\_/\\  ★\n"
    "  ( ^o^ )/\n"
    "  /> ^ <\\\n"
    " /_|___|_\\~~~";
static const char FOX_CELEBRATE_1[] PROGMEM =
    "  ☆/\\_/\\\n"
    "  \\( ^o^ )\n"
    "   /> ^ <\\ ♪\n"
    "  /_|___|_\\~~";
static const char FOX_CELEBRATE_2[] PROGMEM =
    "   /\\_/\\ ✧\n"
    "  ( ^o^ )~\n"
    "  /> ^ <\\♪\n"
    " /_|___|_\\ ~~";
static const char* const FOX_CELEBRATE[] PROGMEM = {FOX_CELEBRATE_0, FOX_CELEBRATE_1, FOX_CELEBRATE_2};

static const char FOX_DIZZY_0[] PROGMEM =
    "   /\\_/\\\n"
    "  ( @.@ )\n"
    "  /> ~ <\\\n"
    " /_|___|_\\ ~";
static const char FOX_DIZZY_1[] PROGMEM =
    "    /\\_/\\\n"
    "   ( ×.× )\n"
    "   /> ~ <\\\n"
    "  /_|___|_\\~";
static const char* const FOX_DIZZY[] PROGMEM = {FOX_DIZZY_0, FOX_DIZZY_1};

static const char FOX_HEART_0[] PROGMEM =
    "   /\\_/\\ ♥\n"
    "  ( ♡.♡ )\n"
    "  /> ^ <\\\n"
    " /_|___|_\\~~";
static const char FOX_HEART_1[] PROGMEM =
    " ♥ /\\_/\\ ♥\n"
    "  ( ♡.♡ )♥\n"
    "  /> ^ <\\\n"
    " /_|___|_\\~~";
static const char* const FOX_HEART[] PROGMEM = {FOX_HEART_0, FOX_HEART_1};

static const PetFrames FOX_PET PROGMEM = {
    "fox",
    FOX_SLEEP, 2,
    FOX_IDLE, 3,
    FOX_BUSY, 2,
    FOX_ATTENTION, 2,
    FOX_CELEBRATE, 3,
    FOX_DIZZY, 2,
    FOX_HEART, 2,
};
