// Auto-generated by tools/convert_pets.py — do not edit by hand.
#pragma once
#include <Arduino.h>
#include "../pet.h"

static const char GHOST_SLEEP_0[] PROGMEM =
    "  .--.  zzZ\n"
    " | -.- |\n"
    " |     |\n"
    "  \\/\\/\\/";
static const char GHOST_SLEEP_1[] PROGMEM =
    "  .--.   zZ\n"
    " | -.- |\n"
    " |     |\n"
    "  \\/\\/\\/";
static const char* const GHOST_SLEEP[] PROGMEM = {GHOST_SLEEP_0, GHOST_SLEEP_1};

static const char GHOST_IDLE_0[] PROGMEM =
    "  .--.\n"
    " | o.o |\n"
    " |     |\n"
    "  \\/\\/\\/";
static const char GHOST_IDLE_1[] PROGMEM =
    "   .--.\n"
    "  | o.o |\n"
    "  |     |\n"
    "   \\/\\/\\/";
static const char GHOST_IDLE_2[] PROGMEM =
    "  .--.\n"
    " | o. o|\n"
    " |     |\n"
    "  \\/\\/\\/";
static const char* const GHOST_IDLE[] PROGMEM = {GHOST_IDLE_0, GHOST_IDLE_1, GHOST_IDLE_2};

static const char GHOST_BUSY_0[] PROGMEM =
    " ~ .--.\n"
    " ~| ◎.◎ |\n"
    "  |     |\n"
    "   \\/\\/\\/";
static const char GHOST_BUSY_1[] PROGMEM =
    "  .--. ~\n"
    " | ◎.◎ |~\n"
    " |     |\n"
    "  \\/\\/\\/";
static const char* const GHOST_BUSY[] PROGMEM = {GHOST_BUSY_0, GHOST_BUSY_1};

static const char GHOST_ATTENTION_0[] PROGMEM =
    "  .--. !\n"
    " | O_O |\n"
    " |     |\n"
    "  \\/\\/\\/";
static const char GHOST_ATTENTION_1[] PROGMEM =
    "  .--. !!\n"
    " | O_O |/\n"
    " |     |\n"
    "  \\/\\/\\/";
static const char* const GHOST_ATTENTION[] PROGMEM = {GHOST_ATTENTION_0, GHOST_ATTENTION_1};

static const char GHOST_CELEBRATE_0[] PROGMEM =
    "  .~~. ★\n"
    " | ^o^ |\n"
    " |     |\n"
    "  \\/\\/\\/";
static const char GHOST_CELEBRATE_1[] PROGMEM =
    " ☆.--.\n"
    " | ^o^ | ♪\n"
    " |     |\n"
    "  \\/\\/\\/";
static const char GHOST_CELEBRATE_2[] PROGMEM =
    "  .~~. ✧\n"
    " | ^o^ |♪\n"
    " |     |\n"
    "  \\/\\/\\/";
static const char* const GHOST_CELEBRATE[] PROGMEM = {GHOST_CELEBRATE_0, GHOST_CELEBRATE_1, GHOST_CELEBRATE_2};

static const char GHOST_DIZZY_0[] PROGMEM =
    " ~.--.\n"
    " | @.@ |\n"
    " |  ~  |\n"
    "  \\/\\/\\/";
static const char GHOST_DIZZY_1[] PROGMEM =
    "  .--. ~\n"
    " | ×.× |\n"
    " | ~   |\n"
    "   \\/\\/\\/ ";
static const char* const GHOST_DIZZY[] PROGMEM = {GHOST_DIZZY_0, GHOST_DIZZY_1};

static const char GHOST_HEART_0[] PROGMEM =
    "  .--. ♥\n"
    " | ♡.♡ |\n"
    " |     |\n"
    "  \\/\\/\\/";
static const char GHOST_HEART_1[] PROGMEM =
    " ♥.--. ♥\n"
    " | ♡.♡ |♥\n"
    " |     |\n"
    "  \\/\\/\\/";
static const char* const GHOST_HEART[] PROGMEM = {GHOST_HEART_0, GHOST_HEART_1};

static const PetFrames GHOST_PET PROGMEM = {
    "ghost",
    GHOST_SLEEP, 2,
    GHOST_IDLE, 3,
    GHOST_BUSY, 2,
    GHOST_ATTENTION, 2,
    GHOST_CELEBRATE, 3,
    GHOST_DIZZY, 2,
    GHOST_HEART, 2,
};
