// Auto-generated by tools/convert_pets.py — do not edit by hand.
#pragma once
#include <Arduino.h>
#include "../pet.h"

static const char OCTOCAT_SLEEP_0[] PROGMEM =
    "  ╱|、\n"
    " (˘ ˘ zzZ\n"
    "  ꜝ |、\n"
    "  ~じし_)ノ";
static const char OCTOCAT_SLEEP_1[] PROGMEM =
    "  ╱|、\n"
    " (˘ ˘  zZ\n"
    "  ꜝ |、\n"
    " ~ じし_)ノ";
static const char* const OCTOCAT_SLEEP[] PROGMEM = {OCTOCAT_SLEEP_0, OCTOCAT_SLEEP_1};

static const char OCTOCAT_IDLE_0[] PROGMEM =
    "  ╱|、\n"
    " (• ω •)\n"
    "  ꜝ |、\n"
    "  ~じし_)ノ";
static const char OCTOCAT_IDLE_1[] PROGMEM =
    "  ╱|、\n"
    " (- ω -)\n"
    "  ꜝ |、\n"
    "  ~じし_)ノ";
static const char OCTOCAT_IDLE_2[] PROGMEM =
    "  ╱|、\n"
    " (• ω •)?\n"
    "  ꜝ |、\n"
    "  ~じし_)ノ";
static const char* const OCTOCAT_IDLE[] PROGMEM = {OCTOCAT_IDLE_0, OCTOCAT_IDLE_1, OCTOCAT_IDLE_2};

static const char OCTOCAT_BUSY_0[] PROGMEM =
    "  ╱|、\n"
    " (◎_◎;)\n"
    "  ꜝ |、⌨\n"
    "  ~じし_)ノ";
static const char OCTOCAT_BUSY_1[] PROGMEM =
    "  ╱|、\n"
    " (◎_◎ )\n"
    "  ꜝ |、 ⌨\n"
    "  ~じし_)ノ";
static const char* const OCTOCAT_BUSY[] PROGMEM = {OCTOCAT_BUSY_0, OCTOCAT_BUSY_1};

static const char OCTOCAT_ATTENTION_0[] PROGMEM =
    "  ╱|、  !\n"
    " (°ω° )\n"
    "  ꜝ |、\n"
    "  ~じし_)ノ";
static const char OCTOCAT_ATTENTION_1[] PROGMEM =
    "  ╱|、 !!\n"
    " (°ω°)/\n"
    "  ꜝ |、\n"
    " ~ じし_)ノ";
static const char* const OCTOCAT_ATTENTION[] PROGMEM = {OCTOCAT_ATTENTION_0, OCTOCAT_ATTENTION_1};

static const char OCTOCAT_CELEBRATE_0[] PROGMEM =
    "  ╱|、 ★\n"
    "\\(^ω^ )/\n"
    "  ꜝ |、\n"
    "  ~じし_)ノ";
static const char OCTOCAT_CELEBRATE_1[] PROGMEM =
    " ☆╱|、\n"
    " (^ω^)ノ\n"
    "  ꜝ |、 ♪\n"
    "  ~じし_)ノ";
static const char OCTOCAT_CELEBRATE_2[] PROGMEM =
    "  ╱|、 ✧\n"
    "\\(^ω^ )\n"
    "  ꜝ |、♪\n"
    " ~ じし_)ノ";
static const char* const OCTOCAT_CELEBRATE[] PROGMEM = {OCTOCAT_CELEBRATE_0, OCTOCAT_CELEBRATE_1, OCTOCAT_CELEBRATE_2};

static const char OCTOCAT_DIZZY_0[] PROGMEM =
    "  ╱|、\n"
    " (@_@ )\n"
    "  ꜝ |、\n"
    " ~ じし_)ノ";
static const char OCTOCAT_DIZZY_1[] PROGMEM =
    "   ╱|、\n"
    "  (×_× )\n"
    "   ꜝ |、\n"
    "  ~じし_)ノ";
static const char* const OCTOCAT_DIZZY[] PROGMEM = {OCTOCAT_DIZZY_0, OCTOCAT_DIZZY_1};

static const char OCTOCAT_HEART_0[] PROGMEM =
    "  ╱|、 ♥\n"
    " (♡ω♡ )\n"
    "  ꜝ |、\n"
    "  ~じし_)ノ";
static const char OCTOCAT_HEART_1[] PROGMEM =
    "  ╱|、♥\n"
    " (♡ω♡)ノ♥\n"
    "  ꜝ |、\n"
    " ~ じし_)ノ";
static const char* const OCTOCAT_HEART[] PROGMEM = {OCTOCAT_HEART_0, OCTOCAT_HEART_1};

static const PetFrames OCTOCAT_PET PROGMEM = {
    "octocat",
    OCTOCAT_SLEEP, 2,
    OCTOCAT_IDLE, 3,
    OCTOCAT_BUSY, 2,
    OCTOCAT_ATTENTION, 2,
    OCTOCAT_CELEBRATE, 3,
    OCTOCAT_DIZZY, 2,
    OCTOCAT_HEART, 2,
};
