// Auto-generated by tools/convert_pets.py — do not edit by hand.
#pragma once
#include <Arduino.h>
#include "../pet.h"

static const char OWL_SLEEP_0[] PROGMEM =
    "  {\\_/}  zzZ\n"
    "  (-.-)>\n"
    "  /|  |\\\n"
    " =='=='==";
static const char OWL_SLEEP_1[] PROGMEM =
    "  {\\_/}   zZ\n"
    "  (-.-)>\n"
    "  /|  |\\\n"
    " =='=='==";
static const char* const OWL_SLEEP[] PROGMEM = {OWL_SLEEP_0, OWL_SLEEP_1};

static const char OWL_IDLE_0[] PROGMEM =
    "  {\\_/}\n"
    "  (O.O)>\n"
    "  /|  |\\\n"
    " =='=='==";
static const char OWL_IDLE_1[] PROGMEM =
    "  {\\_/}\n"
    "  (-.-)>\n"
    "  /|  |\\\n"
    " =='=='==";
static const char OWL_IDLE_2[] PROGMEM =
    "  {\\_/}\n"
    "  (O.o)>\n"
    "  /|  |\\\n"
    " =='=='==";
static const char* const OWL_IDLE[] PROGMEM = {OWL_IDLE_0, OWL_IDLE_1, OWL_IDLE_2};

static const char OWL_BUSY_0[] PROGMEM =
    "  {\\_/}\n"
    "  (◎.◎)>\n"
    "  /| ⌨|\\\n"
    " =='=='==";
static const char OWL_BUSY_1[] PROGMEM =
    "  {\\_/}\n"
    "  (◎.◎;)\n"
    "  /|⌨ |\\\n"
    " =='=='==";
static const char* const OWL_BUSY[] PROGMEM = {OWL_BUSY_0, OWL_BUSY_1};

static const char OWL_ATTENTION_0[] PROGMEM =
    "  {\\_/} !\n"
    "  (O_O)>\n"
    "  /|  |\\\n"
    " =='=='==";
static const char OWL_ATTENTION_1[] PROGMEM =
    "  {\\_/} !!\n"
    "  (O_O)/\n"
    "  /|  |\\\n"
    " =='=='==";
static const char* const OWL_ATTENTION[] PROGMEM = {OWL_ATTENTION_0, OWL_ATTENTION_1};

static const char OWL_CELEBRATE_0[] PROGMEM =
    " ~{\\_/}~ ★\n"
    " \\(^v^)/\n"
    "  /|  |\\\n"
    " =='=='==";
static const char OWL_CELEBRATE_1[] PROGMEM =
    "  {\\_/} ☆\n"
    "  (^v^)> ♪\n"
    "  /|  |\\\n"
    " =='=='==";
static const char OWL_CELEBRATE_2[] PROGMEM =
    " ~{\\_/}~✧\n"
    " \\(^v^)/ ♪\n"
    "  /|  |\\\n"
    " =='=='==";
static const char* const OWL_CELEBRATE[] PROGMEM = {OWL_CELEBRATE_0, OWL_CELEBRATE_1, OWL_CELEBRATE_2};

static const char OWL_DIZZY_0[] PROGMEM =
    "  {\\_/}\n"
    "  (@.@)>\n"
    "  /|  |\\\n"
    "  ='=='= ";
static const char OWL_DIZZY_1[] PROGMEM =
    "   {\\_/}\n"
    "   (×.×)>\n"
    "   /|  |\\\n"
    "  =='=='=";
static const char* const OWL_DIZZY[] PROGMEM = {OWL_DIZZY_0, OWL_DIZZY_1};

static const char OWL_HEART_0[] PROGMEM =
    "  {\\_/} ♥\n"
    "  (♡.♡)>\n"
    "  /|  |\\\n"
    " =='=='==";
static const char OWL_HEART_1[] PROGMEM =
    " ♥{\\_/}♥\n"
    "  (♡v♡)>♥\n"
    "  /|  |\\\n"
    " =='=='==";
static const char* const OWL_HEART[] PROGMEM = {OWL_HEART_0, OWL_HEART_1};

static const PetFrames OWL_PET PROGMEM = {
    "owl",
    OWL_SLEEP, 2,
    OWL_IDLE, 3,
    OWL_BUSY, 2,
    OWL_ATTENTION, 2,
    OWL_CELEBRATE, 3,
    OWL_DIZZY, 2,
    OWL_HEART, 2,
};
