// Auto-generated by tools/convert_pets.py — do not edit by hand.
#pragma once
#include <Arduino.h>
#include "../pet.h"

static const char ROBOT_SLEEP_0[] PROGMEM =
    "    T  zzZ\n"
    "  [_._]\n"
    "  |   |\n"
    " _|___|_";
static const char ROBOT_SLEEP_1[] PROGMEM =
    "    T   zZ\n"
    "  [_._]\n"
    "  |   |\n"
    " _|___|_";
static const char* const ROBOT_SLEEP[] PROGMEM = {ROBOT_SLEEP_0, ROBOT_SLEEP_1};

static const char ROBOT_IDLE_0[] PROGMEM =
    "    *\n"
    "  [o.o]\n"
    "  |   |\n"
    " _|___|_";
static const char ROBOT_IDLE_1[] PROGMEM =
    "    T\n"
    "  [o.o]\n"
    "  |   |\n"
    " _|___|_";
static const char ROBOT_IDLE_2[] PROGMEM =
    "    *\n"
    "  [o. o]\n"
    "  |   |\n"
    " _|___|_";
static const char* const ROBOT_IDLE[] PROGMEM = {ROBOT_IDLE_0, ROBOT_IDLE_1, ROBOT_IDLE_2};

static const char ROBOT_BUSY_0[] PROGMEM =
    "    *\n"
    "  [◎_◎]\n"
    "  |[==]|\n"
    " _|___|_";
static const char ROBOT_BUSY_1[] PROGMEM =
    "    *\n"
    "  [◎_◎]\n"
    "  |[= ]|\n"
    " _|___|_";
static const char* const ROBOT_BUSY[] PROGMEM = {ROBOT_BUSY_0, ROBOT_BUSY_1};

static const char ROBOT_ATTENTION_0[] PROGMEM =
    "    ! \n"
    "  [O_O]\n"
    "  |   |\n"
    " _|___|_";
static const char ROBOT_ATTENTION_1[] PROGMEM =
    "    !!\n"
    "  [O_O]/\n"
    "  |   |\n"
    " _|___|_";
static const char* const ROBOT_ATTENTION[] PROGMEM = {ROBOT_ATTENTION_0, ROBOT_ATTENTION_1};

static const char ROBOT_CELEBRATE_0[] PROGMEM =
    "   ★*\n"
    " \\[^v^]/\n"
    "  |   |\n"
    " _|___|_";
static const char ROBOT_CELEBRATE_1[] PROGMEM =
    "  ☆ *\n"
    "  [^v^]> ♪\n"
    "  |   |\n"
    " _|___|_";
static const char ROBOT_CELEBRATE_2[] PROGMEM =
    "   ✧*\n"
    " \\[^v^]/ ♪\n"
    "  |   |\n"
    " _|___|_";
static const char* const ROBOT_CELEBRATE[] PROGMEM = {ROBOT_CELEBRATE_0, ROBOT_CELEBRATE_1, ROBOT_CELEBRATE_2};

static const char ROBOT_DIZZY_0[] PROGMEM =
    "   ~*~\n"
    "  [@_@]\n"
    "  |ERR|\n"
    " _|___|_";
static const char ROBOT_DIZZY_1[] PROGMEM =
    "    *~\n"
    "  [×_×]\n"
    "  | ER|\n"
    "  _|__|_";
static const char* const ROBOT_DIZZY[] PROGMEM = {ROBOT_DIZZY_0, ROBOT_DIZZY_1};

static const char ROBOT_HEART_0[] PROGMEM =
    "    * ♥\n"
    "  [♡.♡]\n"
    "  | <3|\n"
    " _|___|_";
static const char ROBOT_HEART_1[] PROGMEM =
    "  ♥ * ♥\n"
    "  [♡.♡]\n"
    "  |<3 |\n"
    " _|___|_";
static const char* const ROBOT_HEART[] PROGMEM = {ROBOT_HEART_0, ROBOT_HEART_1};

static const PetFrames ROBOT_PET PROGMEM = {
    "robot",
    ROBOT_SLEEP, 2,
    ROBOT_IDLE, 3,
    ROBOT_BUSY, 2,
    ROBOT_ATTENTION, 2,
    ROBOT_CELEBRATE, 3,
    ROBOT_DIZZY, 2,
    ROBOT_HEART, 2,
};
