#!/usr/bin/env python3
"""Convert CircuitPython pet data to Arduino PROGMEM headers.

Reads pet modules from firmware/circuitpython/pets/ and generates
corresponding .h files in firmware/arduino/copilot_buddy/buddies/.

Usage:
    python tools/convert_pets.py              # convert all pets
    python tools/convert_pets.py octocat fox  # convert specific pets
"""

import importlib.util
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
PETS_SRC = REPO_ROOT / "firmware" / "circuitpython" / "pets"
BUDDIES_DST = REPO_ROOT / "firmware" / "arduino" / "copilot_buddy" / "buddies"

STATES = ["sleep", "idle", "busy", "attention", "celebrate", "dizzy", "heart"]


def escape_c_string(s: str) -> str:
    """Escape a Python string for use inside a C string literal."""
    result = []
    for ch in s:
        if ch == "\\":
            result.append("\\\\")
        elif ch == '"':
            result.append('\\"')
        elif ch == "\t":
            result.append("\\t")
        else:
            result.append(ch)
    return "".join(result)


def load_pet_module(path: Path) -> dict:
    """Import a pet .py file and return its PET dict."""
    spec = importlib.util.spec_from_file_location("pet_mod", str(path))
    if spec is None or spec.loader is None:
        raise ImportError(f"Cannot load {path}")
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)  # type: ignore[union-attr]
    return mod.PET  # type: ignore[attr-defined]


def generate_header(pet: dict) -> str:
    """Generate a C++ PROGMEM header string from a pet data dict."""
    name: str = pet["name"]
    upper = name.upper()
    frames: dict = pet["frames"]

    lines: list[str] = []
    lines.append("// Auto-generated by tools/convert_pets.py — do not edit by hand.")
    lines.append("#pragma once")
    lines.append("#include <Arduino.h>")
    lines.append('#include "../pet.h"')
    lines.append("")

    for state in STATES:
        state_frames = frames.get(state, [])
        state_upper = state.upper()

        # Individual frame strings
        for i, frame in enumerate(state_frames):
            var = f"{upper}_{state_upper}_{i}"
            parts = frame.split("\n")

            if len(parts) <= 1:
                escaped = escape_c_string(frame)
                lines.append(f'static const char {var}[] PROGMEM = "{escaped}";')
            else:
                lines.append(f"static const char {var}[] PROGMEM =")
                for j, part in enumerate(parts):
                    escaped = escape_c_string(part)
                    if j < len(parts) - 1:
                        lines.append(f'    "{escaped}\\n"')
                    else:
                        lines.append(f'    "{escaped}";')

        # Pointer array
        if state_frames:
            ptrs = ", ".join(
                f"{upper}_{state_upper}_{i}" for i in range(len(state_frames))
            )
            lines.append(
                f"static const char* const {upper}_{state_upper}[]"
                f" PROGMEM = {{{ptrs}}};"
            )
        else:
            lines.append(
                f"static const char* const {upper}_{state_upper}[]"
                " PROGMEM = {};"  # empty array fallback
            )
        lines.append("")

    # PetFrames struct
    lines.append(f"static const PetFrames {upper}_PET PROGMEM = {{")
    lines.append(f'    "{name}",')
    for state in STATES:
        state_upper = state.upper()
        count = len(frames.get(state, []))
        lines.append(f"    {upper}_{state_upper}, {count},")
    lines.append("};")
    lines.append("")

    return "\n".join(lines)


def main() -> None:
    if not PETS_SRC.is_dir():
        print(f"Error: pet source directory not found: {PETS_SRC}", file=sys.stderr)
        sys.exit(1)

    BUDDIES_DST.mkdir(parents=True, exist_ok=True)

    if len(sys.argv) > 1:
        pet_names = sys.argv[1:]
    else:
        pet_names = [
            p.stem
            for p in sorted(PETS_SRC.glob("*.py"))
            if p.stem != "__init__"
        ]

    converted = 0
    for pet_name in pet_names:
        src = PETS_SRC / f"{pet_name}.py"
        if not src.exists():
            print(f"Warning: {src} not found, skipping", file=sys.stderr)
            continue

        pet = load_pet_module(src)
        header = generate_header(pet)

        dst = BUDDIES_DST / f"{pet_name}.h"
        dst.write_text(header, encoding="utf-8")
        print(f"  Generated {dst.relative_to(REPO_ROOT)}")
        converted += 1

    print(f"Done — converted {converted} pet(s).")


if __name__ == "__main__":
    main()
